### ISSUE TITLE
Frank Herbert: Dune

### ISSUE THREAD

**Issue by unixmonkey** [getfretless/appendix_n#1]
Who's with me?

**Comment by dstrus** [comment]
I need to finally read Dune.

**Comment by mileszs** [comment]
I enjoyed Dune, but I probably read it too late in life for it to have been very influential. I sort of feel guilty when people rave about it, because I don't feel the same passion.

You know what I will never forget, though? The little sister with all of the knowledge of the many generations of whatever-the-important-holy-women-were-calleds. It was creepy and awesome.

**Comment by unixmonkey** [comment]
The Bene Gesserit.

I found it a bit difficult to get into at first, and I do think I got more out of it when I read it as an adult (or maybe it was the second-pass effect).

The planet is the sole source of what is essentially a smart drug that unlocks telekinesis and space travel for some, that is coveted across the universe, and it's all held on lockdown by terrible people.

Then there's the tribes of nomads that wear suits that recycle their own body fluids that trap and ride sandworms :)

I did try to read the next book in the series, but it couldn't hold my attention. Too much politics.

**Comment by mileszs** [comment]
I forgot about the sweat-and-piss-purifying suits! Hard to forget about the
giant sandworms and the hooks they use to catch a ride.

**Comment by mileszs** [comment]
I am going to add it and close this, as I know Mike also made it a point to indicate how great Dune is when he saw it on my shelf. And the more I think about it, the more fondly I remember the world and the creatures and the culture and such.
